import { Post, Listing, Comment, UserProfile, Seller, Notification } from '@/types';

// Reusable seller profiles
export const mockSellers: Seller[] = [
  {
    id: 's1',
    name: 'ExeterSeller_42',
    rating: 4.8,
    totalSales: 23,
    joinDate: new Date('2024-10-01'),
    listings: ['l1', 'l5'],
  },
  {
    id: 's2',
    name: 'StreathamHills_99',
    rating: 4.5,
    totalSales: 12,
    joinDate: new Date('2025-01-15'),
    listings: ['l2', 'l7'],
  },
  {
    id: 's3',
    name: 'FinalYearClearout',
    rating: 4.9,
    totalSales: 47,
    joinDate: new Date('2024-09-20'),
    listings: ['l3', 'l8'],
  },
  {
    id: 's4',
    name: 'CyclingDave_Exe',
    rating: 4.2,
    totalSales: 8,
    joinDate: new Date('2025-03-01'),
    listings: ['l4'],
  },
  {
    id: 's5',
    name: 'ExeFreshFits',
    rating: 3.9,
    totalSales: 5,
    joinDate: new Date('2025-06-10'),
    listings: ['l6'],
  },
];

export const mockPosts: Post[] = [
  {
    id: '1',
    content: 'Just saw someone bring their cat to the Forum lecture hall and honestly it was the most productive lecture all term. The cat took better notes than me.',
    category: 'confessions',
    reactions: { fire: 234, cap: 12, dead: 89, real: 156, sus: 3 },
    commentCount: 47,
    timestamp: new Date(Date.now() - 1000 * 60 * 23),
    isVerified: true,
    media: [{ type: 'image', url: 'https://picsum.photos/seed/cat1/800/600' }],
  },
  {
    id: '2',
    content: 'The Pret queue at 9am should be classified as a contact sport at this point',
    category: 'hot-takes',
    reactions: { fire: 412, cap: 8, dead: 203, real: 345, sus: 0 },
    commentCount: 82,
    timestamp: new Date(Date.now() - 1000 * 60 * 45),
    isVerified: true,
  },
  {
    id: '3',
    content: '',
    category: 'questions',
    reactions: { fire: 56, cap: 2, dead: 4, real: 78, sus: 0 },
    commentCount: 34,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2),
    isVerified: true,
    poll: {
      question: 'Best study spot on campus?',
      options: [
        { id: 0, text: 'Forum Library', votes: 234 },
        { id: 1, text: 'Old Library', votes: 189 },
        { id: 2, text: 'Reed Hall Café', votes: 312 },
        { id: 3, text: 'My bed (real ones know)', votes: 567 },
      ],
      totalVotes: 1302,
    },
  },
  {
    id: '4',
    content: 'To the person who keeps microwaving fish in the Birks kitchen — we need to talk. Urgently.',
    category: 'rants',
    reactions: { fire: 89, cap: 0, dead: 345, real: 267, sus: 12 },
    commentCount: 63,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 3),
    isVerified: true,
    media: [{ type: 'image', url: 'https://picsum.photos/seed/kitchen/800/600' }],
  },
  {
    id: '5',
    content: 'Hot take: TP is genuinely better than Unit 1 and I will die on this hill',
    category: 'hot-takes',
    reactions: { fire: 123, cap: 456, dead: 34, real: 89, sus: 67 },
    commentCount: 128,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 5),
    isVerified: true,
  },
  {
    id: '6',
    content: 'If you returned my AirPods that I left in the Harrison building, you are genuinely my hero and I owe you a pint at the Ram',
    category: 'confessions',
    reactions: { fire: 45, cap: 0, dead: 0, real: 312, sus: 0 },
    commentCount: 15,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 7),
    isVerified: true,
  },
  {
    id: '7',
    content: '',
    category: 'questions',
    reactions: { fire: 34, cap: 5, dead: 12, real: 45, sus: 0 },
    commentCount: 22,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 8),
    isVerified: true,
    poll: {
      question: 'Should the SU bring back Wednesday sports socials?',
      options: [
        { id: 0, text: 'Yes, obviously', votes: 1245 },
        { id: 1, text: 'No, my liver can\'t cope', votes: 234 },
        { id: 2, text: 'Only if Arena does £1 VKs again', votes: 876 },
      ],
      totalVotes: 2355,
    },
  },
  {
    id: '8',
    content: 'Third year dissertation energy: I have written 47 words today and I am calling it a productive day',
    category: 'memes',
    reactions: { fire: 89, cap: 0, dead: 567, real: 890, sus: 0 },
    commentCount: 93,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 10),
    isVerified: true,
    media: [{ type: 'image', url: 'https://picsum.photos/seed/dissertation/800/600' }],
  },
  {
    id: '9',
    content: 'Free advice: if you\'re thinking of doing a 9am module next term, don\'t. Save yourself. I\'m writing this from my 9am right now and there are 6 people here.',
    category: 'advice',
    reactions: { fire: 234, cap: 12, dead: 145, real: 678, sus: 0 },
    commentCount: 45,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 12),
    isVerified: true,
  },
  {
    id: '10',
    content: 'EVENT: Massive end-of-term house party on Pennsylvania Road. DM for address. BYOB. No first years sorry x',
    category: 'events',
    reactions: { fire: 345, cap: 23, dead: 0, real: 56, sus: 89 },
    commentCount: 67,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 14),
    isVerified: true,
    media: [{ type: 'image', url: 'https://picsum.photos/seed/party/800/600' }],
  },
];

export const mockListings: Listing[] = [
  {
    id: 'l1',
    title: 'MacBook Air M2 — barely used',
    description: 'Bought it for my course but ended up using my iPad instead. Comes with charger, original box. Battery cycle count: 47. Basically brand new.',
    price: 749,
    category: 'electronics',
    images: [
      'https://picsum.photos/seed/macbook/800/800',
      'https://picsum.photos/seed/macbook2/800/800',
      'https://picsum.photos/seed/macbook3/800/800',
    ],
    condition: 'like-new',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2),
    isVerified: true,
    isSold: false,
    sellerKarma: 234,
    seller: { id: 's1', name: 'ExeterSeller_42', rating: 4.8, totalSales: 23, joinDate: new Date('2024-10-01') },
    reviews: [
      { id: 'r1', rating: 5, comment: 'Laptop was exactly as described. Super fast transaction, met at the Forum.', timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5), buyerName: 'buyer_23' },
      { id: 'r2', rating: 4, comment: 'Good seller, was a bit late to the meetup but item was in great condition.', timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24 * 12), buyerName: 'buyer_88' },
    ],
    views: 1247,
    saved: 34,
  },
  {
    id: 'l2',
    title: 'IKEA desk + chair combo',
    description: 'Moving out end of term. MALM desk (white) and MARKUS office chair. Both perfect condition. Collection from Bonhay Road.',
    price: 85,
    category: 'furniture',
    images: [
      'https://picsum.photos/seed/desk/800/800',
      'https://picsum.photos/seed/desk2/800/800',
      'https://picsum.photos/seed/chair/800/800',
    ],
    condition: 'good',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 5),
    isVerified: true,
    isSold: false,
    sellerKarma: 567,
    seller: { id: 's2', name: 'StreathamHills_99', rating: 4.5, totalSales: 12, joinDate: new Date('2025-01-15') },
    reviews: [
      { id: 'r3', rating: 5, comment: 'Desk was spotless. Even helped me carry it to my car. Legend.', timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3), buyerName: 'buyer_14' },
      { id: 'r4', rating: 5, comment: 'Great value, chair is super comfy for long study sessions.', timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24 * 8), buyerName: 'buyer_56' },
      { id: 'r5', rating: 4, comment: 'Minor scratch on the desk that wasn\'t mentioned but otherwise fine.', timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24 * 15), buyerName: 'buyer_71' },
    ],
    views: 832,
    saved: 21,
  },
  {
    id: 'l3',
    title: 'Economics Year 2 Textbooks (full set)',
    description: 'All the core textbooks for BEA2010, BEA2024, BEA2027. Some highlighting in the margins but no structural damage. Will save you over £200 compared to buying new from the bookshop.',
    price: 45,
    category: 'textbooks',
    images: [
      'https://picsum.photos/seed/textbook/800/800',
      'https://picsum.photos/seed/textbook2/800/800',
    ],
    condition: 'good',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 8),
    isVerified: true,
    isSold: false,
    sellerKarma: 123,
    seller: { id: 's3', name: 'FinalYearClearout', rating: 4.9, totalSales: 47, joinDate: new Date('2024-09-20') },
    reviews: [
      { id: 'r6', rating: 5, comment: 'Perfect condition for highlighted books. The notes in the margins actually helped me revise!', timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2), buyerName: 'buyer_32' },
    ],
    views: 456,
    saved: 18,
  },
  {
    id: 'l4',
    title: 'Carrera road bike — just serviced',
    description: 'Perfect for getting up those Exeter hills. Recently serviced at Ride On with new tyres and brake pads. Kryptonite lock included. Ideal for commuting between Streatham and St Luke\'s.',
    price: 180,
    category: 'bikes',
    images: [
      'https://picsum.photos/seed/bike/800/800',
      'https://picsum.photos/seed/bike2/800/800',
      'https://picsum.photos/seed/bike3/800/800',
    ],
    condition: 'good',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 12),
    isVerified: true,
    isSold: false,
    sellerKarma: 890,
    seller: { id: 's4', name: 'CyclingDave_Exe', rating: 4.2, totalSales: 8, joinDate: new Date('2025-03-01') },
    reviews: [
      { id: 'r7', rating: 4, comment: 'Solid bike, handles the hills well. Gears were a tiny bit stiff but nothing major.', timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24 * 10), buyerName: 'buyer_45' },
      { id: 'r8', rating: 5, comment: 'Brilliant bike for the price. Dave even gave me tips on the best cycle routes around campus.', timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24 * 20), buyerName: 'buyer_67' },
    ],
    views: 1890,
    saved: 42,
  },
  {
    id: 'l5',
    title: '2x Arena Saturday tickets — 22 March',
    description: 'Can\'t make it anymore due to a family thing. Face value £8 each, selling both together for £12. Transfer via the venue app — instant and hassle-free.',
    price: 12,
    category: 'tickets',
    images: [
      'https://picsum.photos/seed/tickets/800/800',
      'https://picsum.photos/seed/arena/800/800',
    ],
    condition: 'new',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 3),
    isVerified: true,
    isSold: false,
    sellerKarma: 345,
    seller: { id: 's1', name: 'ExeterSeller_42', rating: 4.8, totalSales: 23, joinDate: new Date('2024-10-01') },
    reviews: [
      { id: 'r9', rating: 5, comment: 'Tickets transferred instantly. Had a great night out!', timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7), buyerName: 'buyer_19' },
    ],
    views: 342,
    saved: 8,
  },
  {
    id: 'l6',
    title: 'North Face Nuptse — Size M',
    description: 'The classic black puffer everyone wants. Worn for one winter season only, no rips or stains whatsoever. Just upgrading to a different jacket. Perfect for those cold walks across campus.',
    price: 140,
    category: 'clothing',
    images: [
      'https://picsum.photos/seed/nuptse/800/800',
      'https://picsum.photos/seed/jacket/800/800',
      'https://picsum.photos/seed/jacket2/800/800',
    ],
    condition: 'like-new',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 6),
    isVerified: true,
    isSold: false,
    sellerKarma: 456,
    seller: { id: 's5', name: 'ExeFreshFits', rating: 3.9, totalSales: 5, joinDate: new Date('2025-06-10') },
    reviews: [
      { id: 'r10', rating: 5, comment: 'Jacket is mint. Looks brand new honestly.', timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24 * 4), buyerName: 'buyer_82' },
      { id: 'r11', rating: 3, comment: 'Took a while to arrange collection but jacket was fine.', timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24 * 14), buyerName: 'buyer_37' },
    ],
    views: 1102,
    saved: 47,
  },
  {
    id: 'l7',
    title: 'Mini fridge — perfect for halls',
    description: 'Russell Hobbs 43L mini fridge in white. Runs quietly so won\'t disturb your flatmates. Fits perfectly under a standard halls desk. Moving to a house with a proper kitchen so no longer need it.',
    price: 35,
    category: 'electronics',
    images: [
      'https://picsum.photos/seed/fridge/800/800',
      'https://picsum.photos/seed/fridge2/800/800',
    ],
    condition: 'good',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 18),
    isVerified: true,
    isSold: false,
    sellerKarma: 67,
    seller: { id: 's2', name: 'StreathamHills_99', rating: 4.5, totalSales: 12, joinDate: new Date('2025-01-15') },
    reviews: [
      { id: 'r12', rating: 4, comment: 'Works great, keeps drinks cold. Bit of a scuff on the side but you can\'t see it under the desk.', timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24 * 6), buyerName: 'buyer_91' },
      { id: 'r13', rating: 5, comment: 'Exactly what I needed for my room in Holland Hall. Cheers!', timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24 * 18), buyerName: 'buyer_05' },
      { id: 'r14', rating: 4, comment: 'Good fridge. Seller was friendly and helped carry it to my car.', timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24 * 25), buyerName: 'buyer_44' },
    ],
    views: 567,
    saved: 15,
  },
  {
    id: 'l8',
    title: 'Vinyl collection — 40+ records',
    description: 'Moving abroad so clearing out my collection. Includes Arctic Monkeys, Tame Impala, Fleetwood Mac, Frank Ocean, and loads more. All in great condition with original sleeves. Happy to sell individually or as a bundle deal.',
    price: 120,
    category: 'other',
    images: [
      'https://picsum.photos/seed/vinyl/800/800',
      'https://picsum.photos/seed/records/800/800',
      'https://picsum.photos/seed/vinyl2/800/800',
    ],
    condition: 'good',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24),
    isVerified: true,
    isSold: false,
    sellerKarma: 789,
    seller: { id: 's3', name: 'FinalYearClearout', rating: 4.9, totalSales: 47, joinDate: new Date('2024-09-20') },
    reviews: [
      { id: 'r15', rating: 5, comment: 'Bought the Frank Ocean vinyl — flawless. This seller has impeccable taste.', timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24 * 1), buyerName: 'buyer_63' },
      { id: 'r16', rating: 5, comment: 'Got the Arctic Monkeys collection. All in perfect nick. Would buy again.', timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24 * 9), buyerName: 'buyer_28' },
      { id: 'r17', rating: 4, comment: 'Great records but one sleeve had a small tear. Still happy overall.', timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24 * 16), buyerName: 'buyer_50' },
      { id: 'r18', rating: 5, comment: 'Absolute bargain for the bundle. My new flat sounds amazing now.', timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24 * 22), buyerName: 'buyer_77' },
    ],
    views: 934,
    saved: 38,
  },
];

export const mockComments: Comment[] = [
  {
    id: 'c1',
    postId: '1',
    content: 'WAS IT A GINGER CAT because I think that\'s Gerald and he lives in the Forum',
    timestamp: new Date(Date.now() - 1000 * 60 * 15),
    upvotes: 89,
    replies: [
      {
        id: 'c1r1',
        postId: '1',
        content: 'Gerald is a campus legend at this point',
        timestamp: new Date(Date.now() - 1000 * 60 * 10),
        upvotes: 45,
        replies: [],
        isOP: false,
      },
    ],
    isOP: false,
  },
  {
    id: 'c2',
    postId: '1',
    content: 'I was in that lecture. The cat literally sat on the lecturer\'s keyboard and opened YouTube.',
    timestamp: new Date(Date.now() - 1000 * 60 * 12),
    upvotes: 234,
    replies: [],
    isOP: true,
  },
  {
    id: 'c3',
    postId: '1',
    content: 'We don\'t deserve Gerald',
    timestamp: new Date(Date.now() - 1000 * 60 * 8),
    upvotes: 67,
    replies: [],
    isOP: false,
  },
];

export const mockProfile: UserProfile = {
  karma: 1247,
  postCount: 23,
  joinDate: new Date('2025-09-15'),
  isVerified: true,
  university: 'University of Exeter',
};

// Comments for all posts
export const allMockComments: Record<string, Comment[]> = {
  '1': [
    {
      id: 'c1',
      postId: '1',
      content: 'WAS IT A GINGER CAT because I think that\'s Gerald and he lives in the Forum',
      timestamp: new Date(Date.now() - 1000 * 60 * 15),
      upvotes: 89,
      replies: [
        {
          id: 'c1r1',
          postId: '1',
          content: 'Gerald is a campus legend at this point',
          timestamp: new Date(Date.now() - 1000 * 60 * 10),
          upvotes: 45,
          replies: [],
          isOP: false,
        },
      ],
      isOP: false,
    },
    {
      id: 'c2',
      postId: '1',
      content: 'I was in that lecture. The cat literally sat on the lecturer\'s keyboard and opened YouTube.',
      timestamp: new Date(Date.now() - 1000 * 60 * 12),
      upvotes: 234,
      replies: [],
      isOP: true,
    },
    {
      id: 'c3',
      postId: '1',
      content: 'We don\'t deserve Gerald',
      timestamp: new Date(Date.now() - 1000 * 60 * 8),
      upvotes: 67,
      replies: [],
      isOP: false,
    },
  ],
  '2': [
    {
      id: 'c4',
      postId: '2',
      content: 'I literally got elbowed trying to get a flat white yesterday',
      timestamp: new Date(Date.now() - 1000 * 60 * 30),
      upvotes: 156,
      replies: [
        {
          id: 'c4r1',
          postId: '2',
          content: 'Should be an Olympic sport at this point',
          timestamp: new Date(Date.now() - 1000 * 60 * 25),
          upvotes: 78,
          replies: [],
          isOP: false,
        },
      ],
      isOP: false,
    },
    {
      id: 'c5',
      postId: '2',
      content: 'Costa in the library is clear, no queue ever',
      timestamp: new Date(Date.now() - 1000 * 60 * 20),
      upvotes: 45,
      replies: [],
      isOP: false,
    },
  ],
  '4': [
    {
      id: 'c6',
      postId: '4',
      content: 'It\'s ALWAYS fish. Every. Single. Time.',
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2),
      upvotes: 201,
      replies: [],
      isOP: false,
    },
    {
      id: 'c7',
      postId: '4',
      content: 'As someone who microwaves fish... no we don\'t need to talk',
      timestamp: new Date(Date.now() - 1000 * 60 * 60),
      upvotes: 312,
      replies: [
        {
          id: 'c7r1',
          postId: '4',
          content: 'Found them. Get them.',
          timestamp: new Date(Date.now() - 1000 * 60 * 55),
          upvotes: 189,
          replies: [],
          isOP: true,
        },
      ],
      isOP: false,
    },
  ],
  '5': [
    {
      id: 'c8',
      postId: '5',
      content: 'The disrespect to Unit 1 is UNREAL',
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 4),
      upvotes: 67,
      replies: [],
      isOP: false,
    },
  ],
  '8': [
    {
      id: 'c9',
      postId: '8',
      content: '47 words? Look at the overachiever over here',
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 9),
      upvotes: 456,
      replies: [],
      isOP: false,
    },
    {
      id: 'c10',
      postId: '8',
      content: 'Currently on word 12 of my literature review. We\'re all going to be fine.',
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 8),
      upvotes: 234,
      replies: [],
      isOP: false,
    },
  ],
  '9': [
    {
      id: 'c11',
      postId: '9',
      content: 'Can confirm. Did a 9am for two terms. Never again.',
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 11),
      upvotes: 123,
      replies: [],
      isOP: false,
    },
  ],
  '10': [
    {
      id: 'c12',
      postId: '10',
      content: '"No first years sorry" is doing heavy lifting in this post',
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 13),
      upvotes: 178,
      replies: [],
      isOP: false,
    },
  ],
};

export const mockNotifications: Notification[] = [
  {
    id: 'n1',
    type: 'reaction',
    title: 'Your yap is on fire',
    body: '234 people reacted to your post about the cat in the Forum',
    timestamp: new Date(Date.now() - 1000 * 60 * 5),
    read: false,
    postId: '1',
  },
  {
    id: 'n2',
    type: 'comment',
    title: 'New comment on your yap',
    body: '"WAS IT A GINGER CAT because I think that\'s Gerald..."',
    timestamp: new Date(Date.now() - 1000 * 60 * 15),
    read: false,
    postId: '1',
  },
  {
    id: 'n3',
    type: 'listing_saved',
    title: 'Someone saved your listing',
    body: '34 people saved "MacBook Air M2 — barely used"',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2),
    read: false,
    listingId: 'l1',
  },
  {
    id: 'n4',
    type: 'reaction',
    title: 'Trending yap',
    body: 'Your hot take about Pret got 412 fire reactions',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 3),
    read: true,
    postId: '2',
  },
  {
    id: 'n5',
    type: 'system',
    title: 'Welcome to YAP',
    body: 'You\'re verified and ready to go. Start yapping!',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24),
    read: true,
  },
  {
    id: 'n6',
    type: 'comment',
    title: 'Reply to your comment',
    body: '"Gerald is a campus legend at this point"',
    timestamp: new Date(Date.now() - 1000 * 60 * 30),
    read: false,
    postId: '1',
  },
];
